build:
  version: "3.0"

cards:
  message: "Welcome to Bank cards related local APIs"
  contactDetails:
    name: "Kio Naji - Developer"
    email: "kionajin@bank.com"
  onCallSupport:
    - (222) 123-0001
    - (222) 321-0002

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cardsdb
    username: root
    password: "{cipher}5bced07e60566680f0efc51275403309a3a525ac7bcf194ab367c1460518423f"
