build:
  version: "3.0"

loans:
  message: "Welcome to Bank loans related local APIs"
  contactDetails:
    name: "Alvarez Fast - Developer"
    email: "alvarezfast@bank.com"
  onCallSupport:
    - (221) 343-7777
    - (111) 777-7773

spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/loansdb
    username: root
    password: "{cipher}5bced07e60566680f0efc51275403309a3a525ac7bcf194ab367c1460518423f"
